### ISSUE TITLE
Sprite assets missing in this repository

### ISSUE THREAD

**Issue by linkmauve** [SnoozeTime/spacegame#1]
Hi, I wanted to package your game in [AUR](https://aur.archlinux.org) (and if you’re interested too, on [Flathub](https://flathub.org/)), but it seems the sprites listed in `src/bin/pack_assets.rs` are missing, preventing it from being built.

I could download the `packed.bin` from your itch.io archive, but that sounds like a pain if it’s possible to build it here.

Thanks, I can’t wait to test this game, it seems exactly like my type!

Edit: I’ve done just that, but spaceships sprites are still missing, for instance I get these errors and can’t see most spaceships at all, making the game pretty much impossible:
```
 ERROR spacegame::assets::sprite > Error while loading spaceships/blue_05.png = No such file or directory (os error 2)
 ERROR spacegame::assets::sprite > Error while loading spaceships/darkgrey_02.png = No such file or directory (os error 2)
 ERROR spacegame::assets::sprite > Error while loading spaceships/metalic_06.png = No such file or directory (os error 2)
 ERROR spacegame::assets::sprite > Error while loading spaceships/red_04.png = No such file or directory (os error 2)
```

Edit 2: Oh I see, the PNGs are embedded in the ELF, this will be a fair bit harder to extract, I’d rather wait for you to publish them in this repository. :)

-- 
[PyTouhou’s author](https://pytouhou.linkmauve.fr/)

**Comment by SnoozeTime** [comment]
Hi there, I am not sure I can put the assets directly on github as they have the following license: https://creativecommons.org/licenses/by/3.0/

As you guessed, you can build the game if you have packed.bin. Then the build can be done with the feature "packed" to embed the assets in the executable. The asset loader is using assets from the `$BASE_ASSET/sprites/` as fallback if cannot find a sprite, so it is possible to make it work with any png by just dropping a PNG image at for example  `$BASE_ASSET/sprites/spaceships/metalic_06.png`

I can manage to find some sprites with a less restrictive license for this repo, but most likely the coherence of the sprites will suffer..

**Comment by linkmauve** [comment]
CC-BY-3.0 isn’t by any mean a restrictive license though, or did you mean some other CC?  It’s only in the case of NC or ND clauses that the entire game would become non-free, but at least it would be possible to package it in Linux distributions.  In any case, existing sprites always beat invisible spaceships! :D

I even thought the entire game was available under that license (as mentioned in [attributions.txt](https://github.com/SnoozeTime/spacegame/blob/master/attributions.txt#L7)), is this not the case?  You may want to add a LICENSE file at the root of your repository stating that clearly.

**Comment by SnoozeTime** [comment]
Actually I was wrong, the license for the assets that are not in github is this one: https://livingtheindie.com/asset-license/
I mailed the artist to get more information about what is possible and what is not.

Good point about this repo license. Will think about a correct one.

**Comment by SnoozeTime** [comment]
I got the permission to include the sprites. Now the full game can be build from the git repo.

**Comment by linkmauve** [comment]
Yay, thanks!  I’ve opened #3 and #4 and once they are merged I think I’ll finish the package in AUR. :)
